export const CHANGE_PLAYERS_NUMBER = 'CHANGE_PLAYERS_NUMBER';
export const CHANGE_PLAYER_NAME = 'CHANGE_PLAYER_NAME';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const SET_POINTS = 'SET_POINTS';