export const CHANGE_PLAYERS_NUMBER = 'CHANGE_PLAYERS_NUMBER';
export const CHANGE_PLAYER_NAME = 'CHANGE_PLAYER_NAME';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const SET_POINTS = 'SET_POINTS';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';